{% set version = "0.7.8" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-questionr
  version: {{ version|replace("-", "_") }}

source:
  fn: questionr_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/questionr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/questionr/questionr_{{ version }}.tar.gz
  sha256: af72e59fe652c6063282a7e5b0f487993b9361cc9ed052a632d64a5a6db76ba9

build:
  noarch: generic
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-classint
    - r-haven >=2.3.0
    - r-highr
    - r-htmltools
    - r-labelled >=2.4.0
    - r-miniui
    - r-rstudioapi
    - r-shiny >=1.0.5
    - r-styler
  run:
    - r-base
    - r-classint
    - r-haven >=2.3.0
    - r-highr
    - r-htmltools
    - r-labelled >=2.4.0
    - r-miniui
    - r-rstudioapi
    - r-shiny >=1.0.5
    - r-styler

test:
  commands:
    - $R -e "library('questionr')"           # [not win]
    - "\"%R%\" -e \"library('questionr')\""  # [win]

about:
  home: https://juba.github.io/questionr/
  license: GPL-2.0-or-later
  summary: 'Set of functions to make the processing and analysis of surveys easier : interactive shiny apps and addins for data recoding, contingency tables, dataset metadata handling, and several convenience functions.'
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
