{% set version = "0.7.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-questionr
  version: {{ version|replace("-", "_") }}

source:
  fn: questionr_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/questionr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/questionr/questionr_{{ version }}.tar.gz
  sha256: c4566880a1ca8f01faad396e20d907d913f4a252acaf83a0cb508a3738874cb3

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-classint
    - r-highr
    - r-htmltools
    - r-labelled >=1.0.0
    - r-miniui
    - r-rstudioapi
    - r-shiny >=1.0.5
  run:
    - r-base
    - r-classint
    - r-highr
    - r-htmltools
    - r-labelled >=1.0.0
    - r-miniui
    - r-rstudioapi
    - r-shiny >=1.0.5

test:
  commands:
    - $R -e "library('questionr')"           # [not win]
    - "\"%R%\" -e \"library('questionr')\""  # [win]

about:
  home: https://juba.github.io/questionr/
  license: GPL (>= 2)
  summary: 'Set of functions to make the processing and analysis of surveys easier : interactive
    shiny apps and addins for data recoding, contingency tables, dataset metadata handling,
    and several convenience functions.'
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
