appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: CWKHDnaVKhzlDbDt7cTuv3RuR1YkvijUc9p02gRvIEyy6/7w8IoGTz0Hu55vDBRd61ItcZQkfBZJGtotuvmca51Zh9VkD1Kiczd8CbacoOz/w+nRBNmoE4r2EgnO3lB9uGACKab3U5mr8Q+3DASzcj5TRLAVjwbRYzx9fsVv07qrl+TdJrIZk14T5Dp2sEXl1C1IuIPMXemLSEq6Oo9U+TWlHyp4Gq8B4DbSeN/blE5YQhHicw2GL3pQFhdR/xZRmaYFv56/RTCDr/UWfMYpr/5Y6634JKZJV0ru1z/3LAHBm1F1CJD8b0oKLqXucbCZ1mTG6uYENxkpxXYLjP6W7vN+GOgGgHRzGGNZSaexyTa2XZVC0RLOWy4UYG0qvBsDe1EB/0I+hYREt3wsXfhK5uVx6scwBSeLGuwdq1f8jhF16bBfyYwzN/NF/erxNuTI06fPP3qYDoNj4XaJtmTUcMzwGY2NVbgqyoJj4NS34N/gpkzi+jQxXtLtrhMDV+1UFDWMb3nZgzjWkgZdkxMVWPlzJmJ31sXeheKOkSXWy+Ux1cbR1lWKhYJDG0LN6eArJk/AfAGo8h1+iU5y7wa4F2yJbozJpfbT4hpM3aq45pWSgw/xtqc69SSMurhqenzxemNA7RjsSFIkdNYImAO7NwYgvJbBB+kDDjgChL6zxQs=
